# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(681, 693)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.calibrateButton = QtGui.QPushButton(self.centralWidget)
        self.calibrateButton.setGeometry(QtCore.QRect(10, 10, 111, 23))
        self.calibrateButton.setObjectName(_fromUtf8("calibrateButton"))
        self.importButton = QtGui.QPushButton(self.centralWidget)
        self.importButton.setGeometry(QtCore.QRect(10, 40, 111, 23))
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.exportButton = QtGui.QPushButton(self.centralWidget)
        self.exportButton.setGeometry(QtCore.QRect(10, 70, 111, 23))
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 16, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 16, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 16, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 16, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 16, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(10, 220, 16, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 16, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(10, 260, 16, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(10, 280, 16, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(10, 300, 16, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(10, 320, 16, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(10, 340, 16, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(10, 360, 16, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(10, 380, 16, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(10, 400, 16, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(10, 420, 16, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.centralWidget)
        self.label_18.setGeometry(QtCore.QRect(10, 440, 16, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.centralWidget)
        self.label_19.setGeometry(QtCore.QRect(10, 460, 16, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.centralWidget)
        self.label_20.setGeometry(QtCore.QRect(10, 480, 16, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.centralWidget)
        self.label_21.setGeometry(QtCore.QRect(10, 500, 16, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.centralWidget)
        self.label_22.setGeometry(QtCore.QRect(10, 520, 16, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.centralWidget)
        self.label_23.setGeometry(QtCore.QRect(10, 540, 16, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.centralWidget)
        self.label_24.setGeometry(QtCore.QRect(10, 560, 16, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.centralWidget)
        self.label_25.setGeometry(QtCore.QRect(10, 580, 16, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.centralWidget)
        self.label_26.setGeometry(QtCore.QRect(10, 600, 16, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.editA = QtGui.QLineEdit(self.centralWidget)
        self.editA.setGeometry(QtCore.QRect(30, 100, 21, 20))
        self.editA.setObjectName(_fromUtf8("editA"))
        self.editB = QtGui.QLineEdit(self.centralWidget)
        self.editB.setGeometry(QtCore.QRect(30, 120, 21, 20))
        self.editB.setObjectName(_fromUtf8("editB"))
        self.editC = QtGui.QLineEdit(self.centralWidget)
        self.editC.setGeometry(QtCore.QRect(30, 140, 21, 20))
        self.editC.setObjectName(_fromUtf8("editC"))
        self.editD = QtGui.QLineEdit(self.centralWidget)
        self.editD.setGeometry(QtCore.QRect(30, 160, 21, 20))
        self.editD.setObjectName(_fromUtf8("editD"))
        self.editE = QtGui.QLineEdit(self.centralWidget)
        self.editE.setGeometry(QtCore.QRect(30, 180, 21, 20))
        self.editE.setObjectName(_fromUtf8("editE"))
        self.editF = QtGui.QLineEdit(self.centralWidget)
        self.editF.setGeometry(QtCore.QRect(30, 200, 21, 20))
        self.editF.setObjectName(_fromUtf8("editF"))
        self.editH = QtGui.QLineEdit(self.centralWidget)
        self.editH.setGeometry(QtCore.QRect(30, 240, 21, 20))
        self.editH.setObjectName(_fromUtf8("editH"))
        self.editG = QtGui.QLineEdit(self.centralWidget)
        self.editG.setGeometry(QtCore.QRect(30, 220, 21, 20))
        self.editG.setObjectName(_fromUtf8("editG"))
        self.editI = QtGui.QLineEdit(self.centralWidget)
        self.editI.setGeometry(QtCore.QRect(30, 260, 21, 20))
        self.editI.setObjectName(_fromUtf8("editI"))
        self.editJ = QtGui.QLineEdit(self.centralWidget)
        self.editJ.setGeometry(QtCore.QRect(30, 280, 21, 20))
        self.editJ.setObjectName(_fromUtf8("editJ"))
        self.editM = QtGui.QLineEdit(self.centralWidget)
        self.editM.setGeometry(QtCore.QRect(30, 340, 21, 20))
        self.editM.setObjectName(_fromUtf8("editM"))
        self.editO = QtGui.QLineEdit(self.centralWidget)
        self.editO.setGeometry(QtCore.QRect(30, 380, 21, 20))
        self.editO.setObjectName(_fromUtf8("editO"))
        self.editL = QtGui.QLineEdit(self.centralWidget)
        self.editL.setGeometry(QtCore.QRect(30, 320, 21, 20))
        self.editL.setObjectName(_fromUtf8("editL"))
        self.editN = QtGui.QLineEdit(self.centralWidget)
        self.editN.setGeometry(QtCore.QRect(30, 360, 21, 20))
        self.editN.setObjectName(_fromUtf8("editN"))
        self.editK = QtGui.QLineEdit(self.centralWidget)
        self.editK.setGeometry(QtCore.QRect(30, 300, 21, 20))
        self.editK.setObjectName(_fromUtf8("editK"))
        self.editP = QtGui.QLineEdit(self.centralWidget)
        self.editP.setGeometry(QtCore.QRect(30, 400, 21, 20))
        self.editP.setObjectName(_fromUtf8("editP"))
        self.editQ = QtGui.QLineEdit(self.centralWidget)
        self.editQ.setGeometry(QtCore.QRect(30, 420, 21, 20))
        self.editQ.setObjectName(_fromUtf8("editQ"))
        self.editR = QtGui.QLineEdit(self.centralWidget)
        self.editR.setGeometry(QtCore.QRect(30, 440, 21, 20))
        self.editR.setObjectName(_fromUtf8("editR"))
        self.editU = QtGui.QLineEdit(self.centralWidget)
        self.editU.setGeometry(QtCore.QRect(30, 500, 21, 20))
        self.editU.setObjectName(_fromUtf8("editU"))
        self.editW = QtGui.QLineEdit(self.centralWidget)
        self.editW.setGeometry(QtCore.QRect(30, 540, 21, 20))
        self.editW.setObjectName(_fromUtf8("editW"))
        self.editT = QtGui.QLineEdit(self.centralWidget)
        self.editT.setGeometry(QtCore.QRect(30, 480, 21, 20))
        self.editT.setObjectName(_fromUtf8("editT"))
        self.editV = QtGui.QLineEdit(self.centralWidget)
        self.editV.setGeometry(QtCore.QRect(30, 520, 21, 20))
        self.editV.setObjectName(_fromUtf8("editV"))
        self.editS = QtGui.QLineEdit(self.centralWidget)
        self.editS.setGeometry(QtCore.QRect(30, 460, 21, 20))
        self.editS.setObjectName(_fromUtf8("editS"))
        self.editX = QtGui.QLineEdit(self.centralWidget)
        self.editX.setGeometry(QtCore.QRect(30, 560, 21, 20))
        self.editX.setObjectName(_fromUtf8("editX"))
        self.editZ = QtGui.QLineEdit(self.centralWidget)
        self.editZ.setGeometry(QtCore.QRect(30, 600, 21, 20))
        self.editZ.setObjectName(_fromUtf8("editZ"))
        self.editY = QtGui.QLineEdit(self.centralWidget)
        self.editY.setGeometry(QtCore.QRect(30, 580, 21, 20))
        self.editY.setObjectName(_fromUtf8("editY"))
        self.ciphertext = QtGui.QPlainTextEdit(self.centralWidget)
        self.ciphertext.setGeometry(QtCore.QRect(130, 10, 541, 310))
        self.ciphertext.setObjectName(_fromUtf8("ciphertext"))
        self.plaintext = QtGui.QPlainTextEdit(self.centralWidget)
        self.plaintext.setGeometry(QtCore.QRect(130, 330, 541, 310))
        self.plaintext.setObjectName(_fromUtf8("plaintext"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 681, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.calibrateButton.setText(_translate("MainWindow", "Calibrate", None))
        self.importButton.setText(_translate("MainWindow", "Import ciphertext", None))
        self.exportButton.setText(_translate("MainWindow", "Export plaintext", None))
        self.label.setText(_translate("MainWindow", "A:", None))
        self.label_2.setText(_translate("MainWindow", "B:", None))
        self.label_3.setText(_translate("MainWindow", "C:", None))
        self.label_4.setText(_translate("MainWindow", "D:", None))
        self.label_5.setText(_translate("MainWindow", "E:", None))
        self.label_6.setText(_translate("MainWindow", "F:", None))
        self.label_7.setText(_translate("MainWindow", "G:", None))
        self.label_8.setText(_translate("MainWindow", "H:", None))
        self.label_9.setText(_translate("MainWindow", "I:", None))
        self.label_10.setText(_translate("MainWindow", "J:", None))
        self.label_11.setText(_translate("MainWindow", "K:", None))
        self.label_12.setText(_translate("MainWindow", "L:", None))
        self.label_13.setText(_translate("MainWindow", "M:", None))
        self.label_14.setText(_translate("MainWindow", "N:", None))
        self.label_15.setText(_translate("MainWindow", "O:", None))
        self.label_16.setText(_translate("MainWindow", "P:", None))
        self.label_17.setText(_translate("MainWindow", "Q:", None))
        self.label_18.setText(_translate("MainWindow", "R:", None))
        self.label_19.setText(_translate("MainWindow", "S:", None))
        self.label_20.setText(_translate("MainWindow", "T:", None))
        self.label_21.setText(_translate("MainWindow", "U:", None))
        self.label_22.setText(_translate("MainWindow", "V:", None))
        self.label_23.setText(_translate("MainWindow", "W:", None))
        self.label_24.setText(_translate("MainWindow", "X:", None))
        self.label_25.setText(_translate("MainWindow", "Y:", None))
        self.label_26.setText(_translate("MainWindow", "Z:", None))
        self.editA.setText(_translate("MainWindow", "a", None))
        self.editB.setText(_translate("MainWindow", "b", None))
        self.editC.setText(_translate("MainWindow", "c", None))
        self.editD.setText(_translate("MainWindow", "d", None))
        self.editE.setText(_translate("MainWindow", "e", None))
        self.editF.setText(_translate("MainWindow", "f", None))
        self.editH.setText(_translate("MainWindow", "h", None))
        self.editG.setText(_translate("MainWindow", "g", None))
        self.editI.setText(_translate("MainWindow", "i", None))
        self.editJ.setText(_translate("MainWindow", "j", None))
        self.editM.setText(_translate("MainWindow", "m", None))
        self.editO.setText(_translate("MainWindow", "o", None))
        self.editL.setText(_translate("MainWindow", "l", None))
        self.editN.setText(_translate("MainWindow", "n", None))
        self.editK.setText(_translate("MainWindow", "k", None))
        self.editP.setText(_translate("MainWindow", "p", None))
        self.editQ.setText(_translate("MainWindow", "q", None))
        self.editR.setText(_translate("MainWindow", "r", None))
        self.editU.setText(_translate("MainWindow", "u", None))
        self.editW.setText(_translate("MainWindow", "w", None))
        self.editT.setText(_translate("MainWindow", "t", None))
        self.editV.setText(_translate("MainWindow", "v", None))
        self.editS.setText(_translate("MainWindow", "s", None))
        self.editX.setText(_translate("MainWindow", "x", None))
        self.editZ.setText(_translate("MainWindow", "z", None))
        self.editY.setText(_translate("MainWindow", "y", None))

